identify_task:
  description: >
    Identify the best natural parks to visit in the West Coast of the United States (California, Utah, Arizona).
    Find the best food to eat in the areas.
    The trip starts on {start_date} and ends on {end_date}.
    Find the best hotels to stay in the areas.
    Do not include any activities that are not related to nature or the outdoors.
    Do not go overboard with the budget, we want to be able to enjoy the trip without breaking the bank.
  input_variables:
    - start_date
    - end_date
  expected_output: >
    A list of the best natural parks to visit in the West Coast of the United States (California, Utah, Arizona)
    A list of the best hotels to stay in the areas

plan_route_task:
  description: >
    Plan the most comfortable and efficient route to visit the selected attractions and activities, taking into account the weather and the traffic, and the best places to eat.
    We will be using a rental car, so we need to find the best places to park the car.
    Keep in mind that we would like to be able to drive to the next destination from the current one.
    We are starting on {start_date} and ending on {end_date}.
    We are departing from Los Angeles, CA, and we will be driving to the selected attractions and activities using a rental car.
    We will return to Los Angeles, CA on {end_date}.
    Do not include any activities that are not related to the selected attractions and activities.
    Do not go overboard with the budget, we want to be able to enjoy the trip without breaking the bank.
    There should be plenty of time to enjoy the trip and not be rushed.
  input_variables:
    - start_date
    - end_date
  expected_output: >
    A trip route with the best places to visit, the best places to eat, and the best places to park the car.
    It should include total distance in kilometers and estimated travel time in hours between each destination.
    It should be a list of destinations with the name of the destination, the distance to the next destination, and the estimated travel time to the next destination.
    It should start and end in Los Angeles, CA.
